name = "telegram-notify"
main = "src/index.ts"
compatibility_date = "2026-04-01"
compatibility_flags = ["nodejs_compat"]
account_id = "95c5c6e1c01ea2d0c9fab69ee9e28462"

routes = [{ pattern = "telegram-notify.la.fish", custom_domain = true }]

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "telegram_notify_events"

[assets]
directory = "./web/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[rules]]
type = "Text"
globs = ["**/*.sql"]
fallthrough = true

[[durable_objects.bindings]]
name = "USER_SCHEDULER"
class_name = "UserSchedulerDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["UserSchedulerDO"]

[env.staging]
name = "telegram-notify-staging"
routes = [{ pattern = "telegram-notify-staging.la.fish", custom_domain = true }]

[[env.staging.durable_objects.bindings]]
name = "USER_SCHEDULER"
class_name = "UserSchedulerDO"

[[env.staging.migrations]]
tag = "v1"
new_sqlite_classes = ["UserSchedulerDO"]

[[env.staging.analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "telegram_notify_events_staging"

[env.staging.assets]
directory = "./web/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
